import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      // `next-env.d.ts` is generated by Next.js on every build. It contains a
      // triple-slash reference by design, and linting a generated file just produces
      // noise that has to be suppressed somewhere.
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
];

export default config;